In [ ]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[3,5],[6,7]])

#addition
c = a + b

print(a)
print(b)
print(c)
print(c.T)

[[1 2]
 [3 4]]
[[3 5]
 [6 7]]
[[ 4  7]
 [ 9 11]]
[[ 4  9]
 [ 7 11]]


In [ ]:
#subtraction
d = a - b
print(d)
print(d.T)

[[-2 -3]
 [-3 -3]]
[[-2 -3]
 [-3 -3]]


In [17]:
#addtion
a = np.array([1,2])
b = np.array([3,4])

c = np.add(a, b)

print(c)

[4 6]


In [18]:
##subtraction

c = np.subtract(b,a)

print(c)

[2 2]


In [22]:
##scalar

s = 3
a = np.array([3,4])

c = np.multiply(s,a)

print(c)


[ 9 12]


In [23]:
#Dot product

u = np.array([[1,2],[3,4]])
v = np.array([[5,6],[7,8]])

c = np.dot(u,v)

print(c)
print(c.T)


[[19 22]
 [43 50]]
[[19 43]
 [22 50]]


In [25]:
#Matrix and vector multiplication

a = ([[3,4],[5,6]])
b = ([1,2])

c = np.dot(a,b)

print(c)


[11 17]


In [29]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a, end=" = a\n\n")
print(a.T, end=" = aT")



[[1 2 3]
 [4 5 6]
 [7 8 9]] = a

[[1 4 7]
 [2 5 8]
 [3 6 9]] = aT

In [32]:
#Create Identity matrix

I1 = np.eye(2)
I2 = np.eye(3)
print(I1, end=" = I1\n\n")
print(I2, end=" = I2\n\n")

[[1. 0.]
 [0. 1.]] = I1

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] = I2



In [ ]:
# Inverse a matrix, given a square matrix a, return the matrix a-inverse satidfying dot(a,ainv) = dot(ainv, a = eye(a.shape[0])).DS_Store

a = np.array([[2,1,0],[0,1,0],[1,2,1]])
print(a, end=" = a\n\n")
print(np.linalg.inv(a), end=" = |a|")